export const RANGE_VALUE_SUCCESS = 'RANGE_VALUE_SUCCESS';
export const INPUT_STRATEGY_SUCCESS = 'INPUT_STRATEGY_SUCCESS';
export const INPUT_STRATEGY_POINTS = 'INPUT_STRATEGY_POINTS';
export const RANDOM_STRATEGY_SUCCESS = 'RANDOM_STRATEGY_SUCCESS';
export const LIFEPOINTS_SUCCESS = 'LIFEPOINTS_SUCCESS';
export const HISTORY_PUSH = 'HISTORY_PUSH';
export const FIELD_VALUE_SUCCESS = 'FIELD_VALUE_SUCCESS';

export const SUCCESS_QUESTIONS_RESULT = 'SUCCESS_QUESTIONS_RESULT';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const FAILURE_RESULT = 'FAILURE_RESULT';
export const SUCCESS_QUIZ_START = 'SUCCESS_QUIZ_START';
export const SUCCESS_QUIZ_END = 'SUCCESS_QUIZ_END';
export const HANDLE_QUESTIONS = 'HANDLE_QUESTIONS';
export const SUCCESS_NEXT_QUESTION = 'SUCCESS_NEXT_QUESTION';
export const INPUT_QUESTION = 'INPUT_QUESTION';
export const ANSWERS_RESULT = 'ANSWERS_RESULT';
export const TEST_REWARDS = 'TEST_REWARDS';

export const USER_BUY_SUCCESS = 'USER_BUY_SUCCESS';
export const SUCCESS_ATTACKS_RESULT = 'SUCCESS_ATTACKS_RESULT';
export const SUCCESS_ABOUT_RESULT = 'SUCCESS_ABOUT_RESULT';
export const SUCCESS_GRUNWALD_RESULT = 'SUCCESS_GRUNWALD_RESULT';

export const SUCCESS_MODAL_FIRST_START = 'SUCCESS_MODAL_FIRST_START';
export const SUCCESS_MODAL_SECOND_START = 'SUCCESS_MODAL_SECOND_START';
export const SUCCESS_MODAL_END = 'SUCCESS_MODAL_END';
export const SELECT_VALUE_SUCCESS = 'SELECT_VALUE_SUCCESS';
export const CHECK_END = 'CHECK_END';
export const USER_RESTART_SUCCESS = 'USER_RESTART_SUCCESS';
